import * as React from "react";
import { Sparkles, ShieldAlert, FileText, RefreshCw } from "lucide-react";

import { AppShell } from "@/components/AppShell";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  AiInsightsAdapter,
  type InsightResult,
} from "@/lib/ai";
import { seededBoardReport } from "@/lib/reporting";
import type { BoardReport } from "@/lib/reporting";
import { cn } from "@/lib/utils";

/** Human-readable copy for each unavailable reason. */
const REASON_COPY: Record<string, string> = {
  "missing-key":
    "No GEMINI_API_KEY is configured, so the AI narrative is turned off. " +
    "Add a key server-side to enable it. The deterministic summary below is " +
    "always available.",
  "browser-blocked":
    "AI insights are generated server-side; the browser never calls the live " +
    "AI provider directly. The deterministic summary below is always available.",
  "http-error":
    "The AI service rejected the request (likely an invalid key or quota). " +
    "Showing the deterministic summary instead.",
  blocked:
    "The AI service declined to generate this narrative. Showing the " +
    "deterministic summary instead.",
  empty:
    "The AI service returned no narrative. Showing the deterministic summary " +
    "instead.",
  malformed:
    "The AI service returned an unexpected response. Showing the " +
    "deterministic summary instead.",
  "network-error":
    "The AI service could not be reached. Showing the deterministic summary " +
    "instead.",
};

export interface InsightsPageProps {
  /** Board report to summarize (defaults to the seeded fixture). */
  report?: BoardReport;
  /**
   * Pre-resolved insight result. When provided, the page renders it directly
   * (used by component tests and the e2e graceful-fallback path) and skips the
   * live adapter call entirely.
   */
  result?: InsightResult;
}

/**
 * AI portfolio narrative panel (`/insights`).
 *
 * Renders a plain-English narrative of the deterministic portfolio state (the
 * board report) produced by the single {@link AiInsightsAdapter}. The adapter
 * reads `GEMINI_API_KEY` server-side; in the browser bundle there is no key, so
 * by default this DEGRADES GRACEFULLY to "AI insights unavailable" plus the
 * deterministic offline summary — never a blank panel and never an error.
 *
 * READ-ONLY: it reads a generated summary; it never moves money or trades.
 */
export function InsightsPage({ report, result }: InsightsPageProps) {
  const data = React.useMemo(() => report ?? seededBoardReport, [report]);

  const [state, setState] = React.useState<InsightResult | null>(
    result ?? null,
  );
  const [loading, setLoading] = React.useState(!result);
  const [nonce, setNonce] = React.useState(0);

  React.useEffect(() => {
    // When a result is injected, render it directly and do not call the adapter.
    if (result) {
      setState(result);
      setLoading(false);
      return;
    }
    let cancelled = false;
    setLoading(true);
    const adapter = new AiInsightsAdapter();
    adapter.narrate(data).then((r) => {
      if (!cancelled) {
        setState(r);
        setLoading(false);
      }
    });
    return () => {
      cancelled = true;
    };
  }, [data, result, nonce]);

  const available = state?.status === "ok";

  return (
    <AppShell
      title={
        <>
          <Sparkles className="size-5 text-[var(--color-chart-up)]" aria-hidden />
          AI portfolio insights
        </>
      }
      titleClassName="flex items-center gap-2"
      width="4xl"
      containerTestId="insights-page"
      backTestId="insights-back"
    >
        <p className="mb-6 text-sm text-muted-foreground" data-testid="insights-asof">
          A plain-English narrative of the portfolio as of {data.asOf} (
          {data.currency}). Generated by the optional Gemini adapter; falls back
          to a deterministic summary when AI is unavailable.
        </p>

        {/* The AI narrative card (or the graceful "unavailable" notice). */}
        <Card data-testid="ai-narrative-card">
          <CardHeader>
            <div className="flex items-center justify-between gap-3">
              <div>
                <CardTitle className="flex items-center gap-2">
                  {available ? (
                    <Sparkles className="size-4" aria-hidden />
                  ) : (
                    <ShieldAlert className="size-4 text-amber-500" aria-hidden />
                  )}
                  AI narrative
                </CardTitle>
                <CardDescription>
                  {available
                    ? `Generated by ${(state as { model?: string }).model ?? "Gemini"}.`
                    : "Optional AI summary (requires a configured key)."}
                </CardDescription>
              </div>
              {!result && (
                <button
                  type="button"
                  data-testid="insights-refresh"
                  onClick={() => setNonce((n) => n + 1)}
                  className="inline-flex items-center gap-1.5 rounded-md border border-border px-2.5 py-1.5 text-xs text-muted-foreground hover:bg-muted"
                >
                  <RefreshCw
                    className={cn("size-3.5", loading && "animate-spin")}
                    aria-hidden
                  />
                  Regenerate
                </button>
              )}
            </div>
          </CardHeader>
          <CardContent>
            {loading ? (
              <p data-testid="insights-loading" className="text-sm text-muted-foreground">
                Generating narrative…
              </p>
            ) : available ? (
              <p data-testid="ai-narrative" className="text-sm leading-relaxed">
                {(state as { narrative: string }).narrative}
              </p>
            ) : (
              <div
                data-testid="ai-unavailable"
                data-reason={
                  state?.status === "unavailable" ? state.reason : undefined
                }
                className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-4"
              >
                <p className="flex items-center gap-2 text-sm font-medium text-amber-600 dark:text-amber-400">
                  <ShieldAlert className="size-4" aria-hidden />
                  AI insights unavailable
                </p>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  {state?.status === "unavailable"
                    ? (REASON_COPY[state.reason] ?? state.detail)
                    : "AI insights are not available."}
                </p>
              </div>
            )}
          </CardContent>
        </Card>

        {/* The deterministic summary is ALWAYS shown, AI or not. */}
        <Card className="mt-6" data-testid="deterministic-card">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FileText className="size-4" aria-hidden />
              Deterministic summary
            </CardTitle>
            <CardDescription>
              Computed directly from the portfolio — always available, offline,
              and reproducible.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <p
              data-testid="deterministic-narrative"
              className="text-sm leading-relaxed text-muted-foreground"
            >
              {state?.deterministic ?? ""}
            </p>
          </CardContent>
        </Card>
    </AppShell>
  );
}

export default InsightsPage;
